# Generated by Django 5.1.4 on 2024-12-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sasa', '0002_remove_userblog_endereco_remove_userblog_nome_bairro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
