# Generated by Django 5.1.4 on 2024-12-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sasa', '0003_alter_userblog_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='carros')),
                ('descricao', models.TextField()),
                ('ano', models.IntegerField()),
            ],
        ),
    ]
